services:
  database:
    image: postgres:16
    container_name: postgres-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PUBLISH_PORT}:5432"
    volumes:
      - fastapi_pgdata:/var/lib/postgresql/data

volumes:
  fastapi_pgdata:
